name: yozil
description: "Booking app."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:

  cloud_firestore: ^5.6.1
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3

  freezed_annotation: ^2.4.4
  go_router: ^14.6.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  json_annotation: ^4.9.0
  lottie: ^3.3.1
  provider: ^6.1.2

dev_dependencies:
  flutter_launcher_icons: "^0.14.2"
  build_runner: ^2.4.14
  freezed: ^2.5.7
  json_serializable: ^6.8.0

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
