// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4vC5A2bozq9Qrbygpu-OCZxl0oIdH__Y',
    appId: '1:82700180448:web:30382e15c767660c52e985',
    messagingSenderId: '82700180448',
    projectId: 'yozil-uz',
    authDomain: 'yozil-uz.firebaseapp.com',
    storageBucket: 'yozil-uz.firebasestorage.app',
    measurementId: 'G-QR5T9P69V7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBevG_ceVAhS_bNehXX1fsBeFpT957M6CQ',
    appId: '1:82700180448:android:a6e58655dfef6d0252e985',
    messagingSenderId: '82700180448',
    projectId: 'yozil-uz',
    storageBucket: 'yozil-uz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAccr9jVfV5lDUlXkoXvXF0Zj4mSFMCLQY',
    appId: '1:82700180448:ios:2cc94382dc2b659552e985',
    messagingSenderId: '82700180448',
    projectId: 'yozil-uz',
    storageBucket: 'yozil-uz.firebasestorage.app',
    iosBundleId: 'uz.yozil.app',
  );

}